repos:
-   repo: https://github.com/gurmukhnishansingh-quilr/quilr-precommit-hooks
    rev: main
    hooks:
    -   id: check-yaml
    -   id: check-attribute
    -   id: check-version
    -   id: validate-schema
    -   id: validate-id
    -   id: check-attribute-tag