-   id: check-yaml
    name: check yaml
    description: checks yaml files for parseable syntax.
    entry: check-yaml
    language: python
    types: [yaml]
-   id: check-attribute
    name: Check attribtue missing
    description: checks if attribute is available
    entry: check-attribute
    language: python
    types: [yaml]
-   id: check-version
    name: Check YAML Version
    entry: check-version
    language: python
    types: [yaml]
    additional_dependencies:
        - packaging
-   id: validate-schema
    name: validate schema
    description: validates yaml files against a schema
    entry: validate-schema
    language: python
    types: [yaml]
    additional_dependencies:
        - jsonschema
        - PyYAML