-   id: check-yaml
    name: check yaml
    description: checks yaml files for parseable syntax.
    entry: check-yaml
    language: python
    types: [yaml]
-   id: check-attribute
    name: Check attribtue missing
    description: checks if attribute is available
    entry: check-attribute
    language: python
    types: [yaml]
-   id: check-version
    name: Check YAML Version
    entry: check-version
    language: python
    types: [yaml]
    additional_dependencies:
        - packaging
-   id: validate-schema
    name: validate schema
    description: validates yaml files against a schema
    entry: validate-schema
    language: python
    types: [yaml]
    additional_dependencies:
        - jsonschema
        - PyYAML
-   id: check-attribute-tags
    name: check attribute tags
    description: checks if attribute tags are present in yaml files
    entry: check-attribute-tags
    language: python
    types: [yaml]
-   id: validate-tags
    name: validate tags
    description: validates tags in yaml files
    entry: validate-tags
    language: python
    types: [yaml]
    additional_dependencies:
        - jsonschema
        - PyYAML
-   id: validate-uuid
    name: validate uuid
    description: validates uuid in yaml files
    entry: validate-uuid
    language: python
    types: [yaml]
    