-   id: check-yaml
    name: check yaml
    description: checks yaml files for parseable syntax.
    entry: check-yaml
    language: python
    types: [yaml]
-   id: check-attribute
    name: Check attribtue missing
    description: checks if attribute is available
    entry: cheeck-attribute
    language: python
    types: [yaml]
-   id: check-version
    name: Check YAML Version
    entry: check_version.py
    language: python
    types: [yaml]
